---
# Useful for local debugging of the scripts.
version: '3.7'

services:
  nexus:
    image: 'sonatype/nexus3:latest'
    container_name: 'nexus'
    user: 'nexus'
    environment:
      NEXUS_SECURITY_RANDOMPASSWORD: 'false'
      NEXUS_CASC_CONFIG: '/opt/nexus.yml'
      #INSTALL4J_ADD_VM_PARAMS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=5005"
    networks:
      - 'nexus'
    ports:
      - '5005:5005'
      - '8081:8081'
      - '18090:18090'
      - '18091:18091'
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - './.circleci/adaptive-nexus.yml:/opt/nexus.yml:ro'
      - './target/nexus-casc-plugin-${PLUGIN_VERSION}-bundle.kar:/opt/sonatype/nexus/deploy/nexus-casc-plugin-${PLUGIN_VERSION}-bundle.kar:ro'
      - 'nexus-data:/nexus-data'

volumes:
  nexus-data:

networks:
  nexus:
